name: Update Global List

on: 
  schedule:
    - cron: '0 4 * * *' # 每天凌晨4点运行
  workflow_dispatch:

jobs:
  update-global-list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch Global.list
      run: |
        curl -o Global.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list

    - name: Fetch EA.list for duplicates
      run: |
        curl -o EA.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list

    - name: Remove duplicate entries from Global.list
      run: |
        grep -vxFf EA.list Global.list > TempGlobal.list && mv TempGlobal.list Global.list

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Global.list
        git commit -m 'Remove duplicate entries based on EA.list'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
